language: emacs-lisp

branches:
  only:
    - master

env:
  - PATH=$HOME/.cask/bin:$PATH

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes -qq emacs-snapshot
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - cask install

script:
  cask exec ert-runner
